export default {
    ADD_TRACK: 'track/add',
    UPDATE_TRACK_NAME: 'track/update_name',
    TOGGLE_TRACK_REMAINING: 'track/toggle_renaming',
    TOGGLE_SEGMENT_VISIBILITY: 'segment/toggle_visibility',
    TOGGLE_SEGMENT_EDITING: 'segment/toggle_edit',
    TOGGLE_SEGMENT_SPLITING: 'segment/toggle_split',
    TOGGLE_SEGMENT_JOINING: 'segment/toggle_join',
    TOGGLE_SEGMENT_POINT_DETAILS: 'segment/toggle_point_details',
    CHANGE_SEGMENT_POINT: 'segment/change_point',
    REMOVE_SEGMENT_POINT: 'segment/remove_point',
    EXTEND_SEGMENT_POINT: 'segment/extend_point',
    ADD_SEGMENT_POINT: 'segment/add_point',
    EXTEND_SEGMENT: 'segment/extend',
    REMOVE_SEGMENT: 'segment/remove',
    SPLIT_SEGMENT: 'segment/split',
    JOIN_SEGMENT: 'segment/join',
}